openapi: 3.0.0
info:
  title: Cheat Buster API
  description: An API to search fake dating profiles by email.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/search:
    get:
      summary: Search for a user by email
      description: |
        Provide an email address to check if it exists in the dating profiles database.
      parameters:
        - in: query
          name: email
          schema:
            type: string
            format: email
          required: true
          description: The email address to search for.
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid email format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          example: 60e6c55b8a6f6f001c8d4b1f
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          example: john.doe@example.com
        age:
          type: integer
          example: 35
        city:
          type: string
          example: New York
        picture:
          type: string
          example: https://randomuser.me/api/portraits/men/75.jpg
    Error:
      type: object
      properties:
        error:
          type: string
          example: Invalid email address
    NotFound:
      type: object
      properties:
        message:
          type: string
          example: Phew! Your partner is not on the list.
